version: '3.7'
services:
    registry:
        image: registry:2
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Realm
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        ports:
            - "5000:5000"
        volumes:
            - ./htpasswd:/auth/htpasswd
            - registry:/var/lib/registry

volumes:
    registry:
